version: 2

sources:
  - name: external
    database: data-talk-clubs
    schema: eu_emissions_project
    tables:
      - name: nitrogen_dioxide_data
        description: "External table for EU nitrogen dioxide emissions data by city"
        external:
          location: "gs://data-talk-clubs-eu-emissions-dev/raw/nitrogen_dioxide_per_city.tsv"
          options:
            format: "CSV"
            field_delimiter: '\t'
            skip_leading_rows: 1
            allow_quoted_newlines: true
            allow_jagged_rows: true
        columns:
          - name: freq_airpol_unit_geo_TIME_PERIOD
            description: "Combined field with frequency, airpol, unit, geo, and time period"
          - name: _2018_01_
            description: "Measurement for 2018-01"
            data_type: STRING
          - name: _2018_02_
            description: "Measurement for 2018-02"
            data_type: STRING
          - name: _2018_03_
            description: "Measurement for 2018-03"
            data_type: STRING
          - name: _2018_04_
            description: "Measurement for 2018-04"
            data_type: STRING
          - name: _2018_05_
            description: "Measurement for 2018-05"
            data_type: STRING
          - name: _2018_06_
            description: "Measurement for 2018-06"
            data_type: STRING
          - name: _2018_07_
            description: "Measurement for 2018-07"
            data_type: STRING
          - name: _2018_08_
            description: "Measurement for 2018-08"
            data_type: STRING
          - name: _2018_09_
            description: "Measurement for 2018-09"
            data_type: STRING
          - name: _2018_10_
            description: "Measurement for 2018-10"
            data_type: STRING
          - name: _2018_11_
            description: "Measurement for 2018-11"
            data_type: STRING
          - name: _2018_12_
            description: "Measurement for 2018-12"
            data_type: STRING
          - name: _2019_01_
            description: "Measurement for 2019-01"
            data_type: STRING
          - name: _2019_02_
            description: "Measurement for 2019-02"
            data_type: STRING
          - name: _2019_03_
            description: "Measurement for 2019-03"
            data_type: STRING
          - name: _2019_04_
            description: "Measurement for 2019-04"
            data_type: STRING
          - name: _2019_05_
            description: "Measurement for 2019-05"
            data_type: STRING
          - name: _2019_06_
            description: "Measurement for 2019-06"
            data_type: STRING
          - name: _2019_07_
            description: "Measurement for 2019-07"
            data_type: STRING
          - name: _2019_08_
            description: "Measurement for 2019-08"
            data_type: STRING
          - name: _2019_09_
            description: "Measurement for 2019-09"
            data_type: STRING
          - name: _2019_10_
            description: "Measurement for 2019-10"
            data_type: STRING
          - name: _2019_11_
            description: "Measurement for 2019-11"
            data_type: STRING
          - name: _2019_12_
            description: "Measurement for 2019-12"
            data_type: STRING
          - name: _2020_01_
            description: "Measurement for 2020-01"
            data_type: STRING
          - name: _2020_02_
            description: "Measurement for 2020-02"
            data_type: STRING
          - name: _2020_03_
            description: "Measurement for 2020-03"
            data_type: STRING
          - name: _2020_04_
            description: "Measurement for 2020-04"
            data_type: STRING
          - name: _2020_05_
            description: "Measurement for 2020-05"
            data_type: STRING
          - name: _2020_06_
            description: "Measurement for 2020-06"
            data_type: STRING
          - name: _2020_07_
            description: "Measurement for 2020-07"
            data_type: STRING
          - name: _2020_08_
            description: "Measurement for 2020-08"
            data_type: STRING
          - name: _2020_09_
            description: "Measurement for 2020-09"
            data_type: STRING
          - name: _2020_10_
            description: "Measurement for 2020-10"
            data_type: STRING
          - name: _2020_11_
            description: "Measurement for 2020-11"
            data_type: STRING
          - name: _2020_12_
            description: "Measurement for 2020-12"
            data_type: STRING
          - name: _2021_01_
            description: "Measurement for 2021-01"
            data_type: STRING
          - name: _2021_02_
            description: "Measurement for 2021-02"
            data_type: STRING
          - name: _2021_03_
            description: "Measurement for 2021-03"
            data_type: STRING
          - name: _2021_04_
            description: "Measurement for 2021-04"
            data_type: STRING
          - name: _2021_05_
            description: "Measurement for 2021-05"
            data_type: STRING
          - name: _2021_06_
            description: "Measurement for 2021-06"
            data_type: STRING
          - name: _2021_07_
            description: "Measurement for 2021-07"
            data_type: STRING
          - name: _2021_08_
            description: "Measurement for 2021-08"
            data_type: STRING
          - name: _2021_09_
            description: "Measurement for 2021-09"
            data_type: STRING
          - name: _2021_10_
            description: "Measurement for 2021-10"
            data_type: STRING
          - name: _2021_11_
            description: "Measurement for 2021-11"
            data_type: STRING
          - name: _2021_12_
            description: "Measurement for 2021-12"
            data_type: STRING
          - name: _2022_01_
            description: "Measurement for 2022-01"
            data_type: STRING
          - name: _2022_02_
            description: "Measurement for 2022-02"
            data_type: STRING
          - name: _2022_03_
            description: "Measurement for 2022-03"
            data_type: STRING
          - name: _2022_04_
            description: "Measurement for 2022-04"
            data_type: STRING
          - name: _2022_05_
            description: "Measurement for 2022-05"
            data_type: STRING
          - name: _2022_06_
            description: "Measurement for 2022-06"
            data_type: STRING
          - name: _2022_07_
            description: "Measurement for 2022-07"
            data_type: STRING
          - name: _2022_08_
            description: "Measurement for 2022-08"
            data_type: STRING
          - name: _2022_09_
            description: "Measurement for 2022-09"
            data_type: STRING
          - name: _2022_10_
            description: "Measurement for 2022-10"
            data_type: STRING
          - name: _2022_11_
            description: "Measurement for 2022-11"
            data_type: STRING
          - name: _2022_12_
            description: "Measurement for 2022-12"
            data_type: STRING
          - name: _2023_01_
            description: "Measurement for 2023-01"
            data_type: STRING
          - name: _2023_02_
            description: "Measurement for 2023-02"
            data_type: STRING
          - name: _2023_03_
            description: "Measurement for 2023-03"
            data_type: STRING
          - name: _2023_04_
            description: "Measurement for 2023-04"
            data_type: STRING
          - name: _2023_05_
            description: "Measurement for 2023-05"
            data_type: STRING
          - name: _2023_06_
            description: "Measurement for 2023-06"
            data_type: STRING
          - name: _2023_07_
            description: "Measurement for 2023-07"
            data_type: STRING
          - name: _2023_08_
            description: "Measurement for 2023-08"
            data_type: STRING
          - name: _2023_09_
            description: "Measurement for 2023-09"
            data_type: STRING
          - name: _2023_10_
            description: "Measurement for 2023-10"
            data_type: STRING
          - name: _2023_11_
            description: "Measurement for 2023-11"
            data_type: STRING
          - name: _2023_12_
            description: "Measurement for 2023-12"
            data_type: STRING
          - name: _2024_01_
            description: "Measurement for 2024-01"
            data_type: STRING
          - name: _2024_02_
            description: "Measurement for 2024-02"
            data_type: STRING
          - name: _2024_03_
            description: "Measurement for 2024-03"
            data_type: STRING
          - name: _2024_04_
            description: "Measurement for 2024-04"
            data_type: STRING
          - name: _2024_05_
            description: "Measurement for 2024-05"
            data_type: STRING
          - name: _2024_06_
            description: "Measurement for 2024-06"
            data_type: STRING
          - name: _2024_07_
            description: "Measurement for 2024-07"
            data_type: STRING
          - name: _2024_08_
            description: "Measurement for 2024-08"
            data_type: STRING
          - name: _2024_09_
            description: "Measurement for 2024-09"
            data_type: STRING
          - name: _2024_10_
            description: "Measurement for 2024-10"
            data_type: STRING
          - name: _2024_11_
            description: "Measurement for 2024-11"
            data_type: STRING
          - name: _2024_12_
            description: "Measurement for 2024-12"
            data_type: STRING
          - name: _2025_01_
            description: "Measurement for 2025-01"
            data_type: STRING
          - name: _2025_02_
            description: "Measurement for 2025-02"
            data_type: STRING
