id: tsv_data_pipeline
namespace: eu.emissions

inputs:
  - id: dataUrls
    name: dataUrls
    type: ARRAY
    itemType: STRING
    description: List of URLs to TSV.GZ files to process

variables:
  file: "temp/data.tsv"
  name: "temp"

tasks:
  - id: loop_over_input_uris
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ inputs.dataUrls }}"
    tasks:
      - id: extract_dataset_id
        type: io.kestra.plugin.scripts.shell.Script
        script: |
          DATASET_ID=$(echo "{{ taskrun.value }}" | grep -oP '(?<=/data/)[^?]+')
          echo "$DATASET_ID" > /tmp/dataset_id.txt
        outputFiles:
          - /tmp/dataset_id.txt
        description: "Extract dataset ID from URL"

      - id: extract
        type: io.kestra.plugin.scripts.shell.Commands
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
        commands:
          - curl -L "{{ taskrun.value }}" | gunzip >> data.tsv
        outputFiles:
          - data.tsv
        description: "Download and decompress TSV.GZ file"
      #      - id: download_and_decompress
      #        type: io.kestra.plugin.scripts.shell.Script
      #        script: |
      #          curl -L "{{ taskrun.value }}" > "/tmp/data.tsv"
      #        outputFiles:
      #          - /tmp/data.tsv
      #        description: "Download and decompress TSV.GZ file"

      - id: upload_to_gcs
        type: io.kestra.plugin.gcp.gcs.Upload
        from: "{{ outputs.extract.outputFiles['data.tsv'] }}" #"{{ outputs.grab_data.outputFiles['/tmp/data.tsv'] }}"
        to: "gs://data-talk-clubs-eu-emissions-dev/{{ render(vars.name) }}/data.tsv"
        description: "Upload decompressed TSV file to GCS"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 * * *" # Run daily at midnight


    # ["https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/env_ac_ainah_r2?format=TSV&compressed=true","https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/env_ac_aibrid_r2?format=TSV&compressed=true","https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/env_ac_aeint_r2?format=TSV&compressed=true"]
